#!/usr/bin/env bash
# vim: ft=bash ts=2 sw=2 sts=2 et :
 
here="$(git rev-parse --show-toplevel)"

alias ..='cd ..'
alias ...='cd ../../../'

alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias gp="git add *;git commit -am save;git push;git status"
alias grep='grep --color=auto'
alias h="history"
alias hi="git pull"
alias ls="ls -G"
alias vi="vim -u $here/etc/dotvimrc "
alias vims="vim +PluginInstall +qall"         

export BASH_SILENCE_DEPRECATION_WARNING=1
export PATH="$PWD:/opt/homebrew/bin:$PATH"
export EDITOR=$(which pico)

here() { cd $1; basename `pwd`; }

PROMPT_COMMAND='echo -ne "👩  $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'

clear
tput bold; tput setaf 3
cat<<-'EOF'
                               ___       ___     
                             /'___`\   /'___`\   
   __      ____     __      /\_\ /\ \ /\_\ /\ \  
 /'__`\   /',__\  /'__`\    \/_/// /__\/_/// /__ 
/\ \L\.\_/\__, `\/\  __/       // /_\ \  // /_\ \
\ \__/.\_\/\____/\ \____\     /\______/ /\______/
 \/__/\/_/\/___/  \/____/     \/_____/  \/_____/ 

EOF
tput bold; tput setaf 241
echo "Short cuts:"
alias | sed 's/alias /  /'
echo ""
tput sgr0
